function render_mitsuba1(mitsuba_dir, out_dir, xml_dir, tab_bin_dir)
    if isempty(tab_bin_dir)
        cmd = [mitsuba_dir ...
            ' -o ' out_dir ...
            ' ' xml_dir]
    else
        cmd = [mitsuba_dir ...
            ' -Dfn=' tab_bin_dir ...
            ' -o ' out_dir ...
            ' ' xml_dir]
    end        
    system(cmd);
end
