function render_mitsuba1(mitsuba_dir, out_dir, xml_dir, scale, sigma_t, albedo, tab_bin_dir)
    if isempty(tab_bin_dir)
        cmd = [mitsuba_dir ...
            ' -o ' out_dir ...
            ' ' xml_dir]
    else
        cmd = [mitsuba_dir ...
            ' -p 12' ...
            ' -Dscale=' num2str(scale) ...
            ' -Dsigma_t=' num2str(sigma_t) ...
            ' -Dalbedo=' num2str(albedo) ...
            ' -Dfn=' tab_bin_dir ...
            ' -o ' out_dir ...
            ' ' xml_dir]
    end        
    system(cmd);
end
