function render_mitsuba2(mitsuba_dir, out_dir, xml_dir, use_gpu, tab_bin_dir)
    gpu_flag = 'scalar_rgb';   
    if use_gpu
        gpu_flag = 'gpu_rgb';
    end 
    if isempty(tab_bin_dir)
        cmd = [mitsuba_dir ...
            ' -m ' gpu_flag ...
            ' -o ' out_dir ...
            ' ' xml_dir]
    else
        cmd = [mitsuba_dir ...
            ' -m ' gpu_flag ...
            ' -Dfn=' tab_bin_dir ...
            ' -o ' out_dir ...
            ' ' xml_dir]
    end        
    system(cmd);
end
