function render_mitsuba2(mitsuba_dir, out_dir, xml_dir, use_gpu, scale, sigma_t, albedo, tab_bin_dir)
    gpu_flag = 'scalar_rgb';   
    if use_gpu
        gpu_flag = 'gpu_rgb';
    end 
    cmd = [mitsuba_dir ...
        ' -m ' gpu_flag ...
        ' -t 12' ...
        ' -Dscale=' num2str(scale) ...
        ' -Dsigma_t=' num2str(sigma_t) ...
        ' -Dalbedo=' num2str(albedo) ...
        ' -Dfn=' tab_bin_dir ...
        ' -o ' out_dir ...
        ' ' xml_dir];
    system(cmd);
end
